#! /bin/bash

. ./setup_environment
timestamp_start

case $GHC_VERSION in
    710)
        ghcjs-boot --dev
        ;;
    *)
        echo "Invalid GHC_VERSION : $GHC_VERSION"
        ;;
esac

timestamp_finish
