FROM ubuntu:vivid

RUN mkdir /workarea
WORKDIR /workarea

# Set the locale - was (and may still be ) necessary for ghcjs-boot to work
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

##################################
##### Quick and minimal set ######
##### of developer's tools. ######
##################################
ADD setup_bash_startup /workarea/
RUN ./setup_bash_startup 

ADD install_devl_tools /workarea/
RUN ./install_devl_tools 

ADD setup_sshd /workarea/
RUN ./setup_sshd 

ADD setup_vim_plugins /workarea/
RUN ./setup_vim_plugins 

ADD install_atom /workarea/
RUN ./install_atom 

EXPOSE 22
EXPOSE 8000
ENTRYPOINT ["/usr/bin/svscan", "/services/"]

##################################
##### Install ghc ################
##################################
ADD setup_environment /workarea/

ADD install_prerequisites /workarea/
RUN ./install_prerequisites 

ADD install_cabal_from_source /workarea/
RUN ./install_cabal_from_source -b cabal-install-v1.22.6.0 

ADD install_alex_and_happy /workarea/
RUN ./install_alex_and_happy 

ADD install_ghc /workarea/
RUN ./install_ghc -v 710 -b ghc-7.10.2-release

ADD install_haskell_devl_tools /workarea/
RUN ./install_haskell_devl_tools -v 710

ADD setup_stack /workarea/
RUN ./setup_stack -v 710

##################################
##### Install ghcjs ##############
##################################
ADD install_node /workarea/
RUN ./install_node -b v0.12.7-release 

ADD install_ghcjs /workarea/
RUN ./install_ghcjs 

ADD boot_ghcjs /workarea/
RUN ./boot_ghcjs -v 710 

ADD install_typescript /workarea/
RUN ./install_typescript 

###########################################
#####                                 #####
#####    Personal Customization       #####
#####                                 #####
###########################################
ADD personalize /workarea/
RUN ./personalize

