#! /bin/bash

. ./setup_environment
timestamp_start

apt-get update

## basics
apt-get install -y \
    daemontools \
    git \
    openssh-server \
    tmux \
    vim-gtk

## needed for ghc & ghcjs
apt-get install -y \
    autoconf  \
    automake  \
    bison \
    bzip2  \
    curl \
    dblatex  \
    docbook-utils  \
    docbook-xsl  \
    g++  \
    git  \
    haskell-platform  \
    libcurl4-openssl-dev \
    libdbd-sqlite3-perl \
    libdbi-perl \
    libgmp-dev  \
    libtool  \
    libwww-curl-perl \
    libxml2-utils  \
    linux-tools-generic  \
    make  \
    ncurses-dev  \
    net-tools \
    nodejs  \
    nodejs-legacy  \
    npm  \
    pkg-config \
    python  \
    sudo  \
    texlive-font-utils \
    xutils-dev 

## needed for nix
apt-get install -y \
    bison \
    curl \
    libcurl4-openssl-dev \
    libdbd-sqlite3-perl \
    libdbi-perl \
    libwww-curl-perl \
    pkg-config \
    sudo  

timestamp_finish
