#! /bin/bash

. setup_environment

git clone https://github.com/ghcjs/ghcjs.git 
git clone https://github.com/ghcjs/ghcjs-prim.git 
cabal install --reorder-goals --max-backjumps=-1 ./ghcjs ./ghcjs-prim
