#! /bin/bash

. ./setup_environment
timestamp_start

touch /root/.bashrc
cat >> /root/.bashrc << EOF
. ~/startup
EOF

touch ~/startup
touch ~/aliases

cat >> /root/startup << EOF
. ~/aliases

export PATH=\
/root/.cabal/bin:\
\$PATH
EOF

timestamp_finish
