#! /bin/bash

. ./setup_environment
timestamp_start

touch $HOME/.bashrc
cat >> $HOME/.bashrc << EOF
. ~/startup
EOF

touch ~/startup
touch ~/aliases

cat >> $HOME/startup << EOF
. ~/aliases

export PATH=\
$HOME/.cabal/bin:\
\$PATH
EOF

timestamp_finish
