#! /bin/bash
. ./setup_environment
timestamp_start

mkdir -p $HOME/.vim/autoload

#### pathogen
cd /tmp
git clone https://github.com/tpope/vim-pathogen.git
cp vim-pathogen/autoload/pathogen.vim $HOME/.vim/autoload
rm -rf vim-pathogen
mkdir -p $HOME/.vim/bundle

cd $HOME/.vim/bundle

#### syntastic
git clone https://github.com/scrooloose/syntastic.git

#### vim-hdevtools
git clone https://github.com/bitc/vim-hdevtools.git

#### vim2hs
git clone https://github.com/dag/vim2hs.git

#### vim startup
touch $HOME/.vimrc
cat >> $HOME/.vimrc << EOF
so ~/myVimrc
EOF

cat > $HOME/myVimrc << EOF
" pathogen related
execute pathogen#infect()
syntax on
filetype plugin indent on

" syntastic related
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 '

map <silent> <Leader>e :Errors<CR>
map <Leader>s :SyntasticToggleMode<CR>
" let g:syntastic_auto_loc_list=1

" vim2hs related
set nofoldenable

" vim-hdevtools/hdevtools related
au FileType haskell nnoremap <buffer> <F2> :HdevtoolsType<CR>
au FileType haskell nnoremap <buffer> <silent> <F3> :HdevtoolsClear<CR>
au FileType haskell nnoremap <buffer> <silent> <F4> :HdevtoolsInfo<CR>
EOF

timestamp_finish
