#! /bin/bash

. ./setup_environment
timestamp_start

mkdir -p /services/sshd /var/run/sshd 

cat > /services/sshd/run << EOF
#!/bin/bash
exec /usr/sbin/sshd
EOF

chmod +x /services/sshd/run
sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

timestamp_finish
