#! /bin/bash

. ./setup_environment

sudo apt-get update && sudo apt-get install haskell-platform -y

cabal update 
git clone -b ${GIT_BRANCH} git://github.com/haskell/cabal.git 
cd cabal
cabal install Cabal/ cabal-install/ 

