#! /bin/bash

. ./setup_environment

cabal update

sudo apt-get update && sudo apt-get install -y \
    git \
    apt-utils \
    libbz2-dev

git clone https://github.com/valderman/haste-compiler.git -b ${GIT_BRANCH}
cd haste-compiler
cabal install
haste-boot --force --local

