#! /bin/bash

. ./setup_environment

sudo apt-get update && sudo apt-get install haskell-platform git autoconf automake libtool make libgmp-dev ncurses-dev g++ python bzip2 -y

git clone -b $GIT_BRANCH  --recursive git://git.haskell.org/ghc.git 
cd ghc

cat mk/build.mk.sample  | sed -e '/#Build.*quick$/s/^#//' > mk/build.mk 
./boot 
./configure 
make 
sudo make install
