#! /bin/bash

. ./setup_environment
timestamp_start

ghc_and_ghcjs_prereq=" \
    bison \
    curl \
    dblatex  \
    docbook-utils  \
    docbook-xsl  \
    libcurl4-openssl-dev \
    libdbd-sqlite3-perl \
    libdbi-perl \
    libwww-curl-perl \
    libxml2-utils  \
    linux-tools-generic  \
    pkg-config \
    texlive-font-utils \
    unzip \
    xutils-dev \
    zip "

sudo apt-get update

for s in apt-utils $ghc_and_ghcjs_prereq; do
    echo "apt-get INSTALLING $s"
    sudo apt-get install -y $s
done 

timestamp_finish
