#! /bin/bash

. ./setup_environment
timestamp_start

sudo apt-get update && sudo apt-get install python make g++ -y

git clone -b $GIT_BRANCH https://github.com/joyent/node.git 
cd node
./configure 
make 
sudo make install 

timestamp_finish
