#! /bin/bash

sudo mkdir -p /services/sshd /var/run/sshd 

cat << EOF | sudo tee /services/sshd/run 
#!/bin/bash
exec /usr/sbin/sshd
EOF

sudo chmod +x /services/sshd/run
sudo sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
