#! /bin/bash

# This script starts a docker container that runs start.sh .
# The name and id of the current user are passed to start.sh so that start.sh
# can create a user with the same name and id inside the docker image.

DOCKER_ARGUMENTS=$*
echo $DOCKER_ARGUMENTS

# Technique for start dir thanks to http://stackoverflow.com/a/246128/509928 .
RELATIVE_START_DIR="$( dirname "${BASH_SOURCE[0]}" )"
START_DIR="$( cd $RELATIVE_START_DIR && pwd )"

START_SCRIPT=start.sh

if [[ ! -e $START_DIR/$START_SCRIPT ]]; then
    echo "$0 expects $RELATIVE_START_DIR/$START_SCRIPT to be present."
    exit -1
fi

USER_NAME=`id -u -n`
USER_ID=`id -u`

exec sudo /usr/bin/docker run -v $START_DIR:/start --entrypoint /start/$START_SCRIPT $DOCKER_ARGUMENTS $USER_NAME $USER_ID
