#! /bin/bash
cd /start

mkdir -p $HOME/.ssh
cp authorized_keys $HOME/.ssh
cp startup $HOME

touch $HOME/.bashrc
cat >> $HOME/.bashrc << EOF
. ~/startup
EOF

## Use the vim plugins installed at docker build.
for s in .cabal .ghc .ghcjs .haste .vim .vimrc; do
    ln -s /home/ghc/$s $HOME
done
